---
deployment:
 tasks:
 - export DEPLOYPATH_ORIGINAL=/home/sciwalker/public_html/
 - /bin/cp README.md $DEPLOYPATH_ORIGINAL
 - /bin/cp header_2018.html $DEPLOYPATH_ORIGINAL
 - /bin/cp home.php $DEPLOYPATH_ORIGINAL
 - export DEPLOYPATH_ASSET=/home/sciwalker/public_html/assets/img/
 - /bin/cp assets/img/test.py $DEPLOYPATH_ASSET
 - export DEPLOYPATH_FOLDER=/home/sciwalker/merchandise/
 - /bin/cp merchandise/* $DEPLOYPATH_FOLDER
#  - /bin/cp style.css $DEPLOYPATH
