---
deployment:
 tasks:
 - export DEPLOYPATH=/home/sciwalker/public_html/
 - /bin/cp README.md $DEPLOYPATH
 - export DEPLOYPATH_ASSETS=/home/sciwalker/public_html/assets/img/
 - /bin/cp test.py $DEPLOYPATH_ASSETS
#  - /bin/cp style.css $DEPLOYPATH
