---
deployment:
 tasks:
 - export DEPLOYPATH_ORIGINAL=/home/sciwalker/public_html/
 - /bin/cp README.md $DEPLOYPATH_ORIGINAL
 - /bin/cp header_2018.html $DEPLOYPATH_ORIGINAL
 - /bin/cp home.php $DEPLOYPATH_ORIGINAL
 - export DEPLOYPATH=/home/sciwalker/public_html/assets/img/
 - /bin/cp assets/img/test.py $DEPLOYPATH
#  - /bin/cp style.css $DEPLOYPATH
