---
deployment:
 tasks:
#  - export DEPLOYPATH=/home/sciwalker/public_html/
#  - /bin/cp README.md $DEPLOYPATH
 - export DEPLOYPATH=/home/sciwalker/public_html/assets/img/
 - /bin/cp assets/img/test.py $DEPLOYPATH
#  - /bin/cp style.css $DEPLOYPATH
