---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sciwalker/public_html/tech
    - /bin/cp -R tech/qr_code $DEPLOYPATH
    - export DEPLOYPATH_ORIGINAL=/home/sciwalker/public_html/
    - /bin/cp header_2018.html $DEPLOYPATH_ORIGINAL


