---
deployment:
 tasks:
 - export DEPLOYPATH_ORIGINAL=/home/sciwalker/public_html/
 - /bin/cp Natalic.ttf $DEPLOYPATH_ORIGINAL
 - /bin/cp robots.txt $DEPLOYPATH_ORIGINAL
 - /bin/cp technologies.php $DEPLOYPATH_ORIGINAL
  - /bin/cp README.md $DEPLOYPATH_ORIGINAL
#  - /bin/cp merchandise/educational_puzzles.php $DEPLOYPATH_ORIGINAL
 - /bin/cp footer_2018.html $DEPLOYPATH_ORIGINAL
 - /bin/cp Simulations.php $DEPLOYPATH_ORIGINAL
#  - /bin/cp "formula-derivation-metre-rule-balanced-curved-surface.php" $DEPLOYPATH_ORIGINAL
#  - /bin/cp -R "Physics Articles" $DEPLOYPATH_ORIGINAL
#  - /bin/cp -R merchandise $DEPLOYPATH_ORIGINAL
 - /bin/cp -R tech $DEPLOYPATH_ORIGINAL
 - export DEPLOYPATH_ASSET=/home/sciwalker/public_html/assets/img/
 - /bin/cp assets/img/logo/logo-phymath.png $DEPLOYPATH_ASSET
#  - export DEPLOYPATH_FOLDER=/home/sciwalker/public_html/merchandise/
#  - /bin/cp style.css $DEPLOYPATH
